name: Dependents
on:
  workflow_run:
    workflows: [ "Publish" ]
    branches: [ master ]
    types:
      - completed

jobs:
  vpe-hdrp:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout vpe.assets
        uses: actions/checkout@v2
        with:
           path: VisualPinball.Unity.AssetLibrary
      - name: Checkout vpe.hdrp
        uses: actions/checkout@v2
        with:
           repository: VisualPinball/VisualPinball.Unity.Hdrp
           path: VisualPinball.Unity.Hdrp
           token: ${{ secrets.GH_PAT }}
      - name: Update Dependent
        id: updateDependent
        uses: VisualPinball/update-dependent-action@v0.1.0
        with:
          source: VisualPinball.Unity.AssetLibrary
          dependent: VisualPinball.Unity.Hdrp
      - name: Commit 
        if: ${{ steps.updateDependent.outputs.isBump == 'true' }} 
        run: |
          cd VisualPinball.Unity.Hdrp
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore(deps): Update ${{ steps.updateDependent.outputs.sourceName }} to ${{ steps.updateDependent.outputs.sourceVersion }}."
          git push