name: Publish
on: 
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true 
      - name: Fetch next version
        id: nextVersion
        uses: VisualPinball/next-version-action@v0.1.6
        with:
          tagPrefix: 'v'
      - name: Bump
        if: ${{ steps.nextVersion.outputs.isBump == 'true' }} 
        run: |
          npm version ${{ steps.nextVersion.outputs.nextVersion }} --no-git-tag-version    
      - name: Commit
        id: commit
        if: ${{ steps.nextVersion.outputs.isBump == 'true' }} 
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "release: ${{ steps.nextVersion.outputs.nextTag }}."
          git push
          commitish=$(git rev-parse HEAD)
          echo ::set-output name=commitish::${commitish}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.nextVersion.outputs.nextTag }}
          release_name: ${{ steps.nextVersion.outputs.nextTag }}
          prerelease: ${{ steps.nextVersion.outputs.isPrerelease }}
          commitish: ${{ steps.commit.outputs.commitish }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Dummy Archive
        run: |
          echo "//registry.visualpinball.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm pack
          echo "NPM_ARCHIVE=$(ls org.visualpinball.unity.assetlibrary*.tgz)" >> $GITHUB_ENV
          rm -rf Assets
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload Real Archive
        uses: appleboy/scp-action@master
        with:
          host: registry.visualpinball.org
          port: 22
          username: ${{ secrets.REGISTRY_SSH_USERNAME }}
          key: ${{ secrets.REGISTRY_SSH_KEY }}
          source: ${{ env.NPM_ARCHIVE }}
          target: ${{ secrets.REGISTRY_SSH_PATH }}
